### ISSUE TITLE
l. Message d'alerte lors de la suppression des traces de l'étudiant

### ISSUE THREAD

**Issue by AdrienPrugnaud** [EsupPortail/KAPC#13]
Informer l’étudiant que s’il modifie un lien ou un fichier dans un trace qu’il faudra qu’il supprime la trace dans la page action telle qu’une saé sinon le lien depuis la page saé vers le fichier dans la trace ne fonctionnera plus => bug ? les étudiants ont peut-être supprimé la trace alors qu’elle été déjà associée et ils ont du en faire une nouvelle nommée pareil ? Quelle solution car on ne peut pas vérifier si elle est utilisée ou non ? A étudier et ajouter une popup qui averti l’utilisateur lorsque l’étudiant supprime la trace ça peut poser un pb si elle est associée ailleurs / vérifier quand il supprime si elle est associée ailleurs (et le fichier dans une trace ?) / A tester et à reproduire.  KAPC 1.3

**Comment by olivier-gerbe** [comment]
Si l'étudiant supprime une tracée que cette trace est utilisée, il y a un message lui demandant si il veut vraiment la supprimer, si oui on supprime toutes les utilisations de la trace.

**Comment by AdrienPrugnaud** [comment]
Le test est ajouté dans les traces existantes via le batch de 1.2 à 1.3. Tests Adrien ok
