### ISSUE TITLE
N. Agenda/rapport des dates butoirs d'évaluation des étudiants

### ISSUE THREAD

**Issue by AdrienPrugnaud** [EsupPortail/KAPC#15]
Avoir un rapport pour l’étudiant lui-même qui lui présente l’ensemble des saé avec les dates de soumissions butoir des évaluations pour chaque saé (ajouter une date buttoir de demande d’évaluation par l’étudiant dans la fiche saé, stage ou alternance ?). Ils voudraient un agenda…
Introduire une date butoir éditable par l’étudiant en fonction de ce qu’a demandé l’enseignant et afficher un rapport des saé triées / triables par date ? KAPC 1.3

**Comment by giraudin** [comment]
La fonctionnalité a bien été implémentée mais il faudrait que l'étudiant puisse supprimer ensuite dans son agenda ces dates ou n'afficher que celle qui ne sont pas encore dépassées

**Comment by isabelle-roy** [comment]
La SAé disparait de l'agenda lorsque l'enseignant soumet son évaluation.
