### ISSUE TITLE
V. Ajouter information tableau des bilans multi compétences

### ISSUE THREAD

**Issue by giraudin** [EsupPortail/KAPC#23]
Ajouter dans les pages tableau de bord des bilans de formations ou personnalisées l'information suivante :

> NB : **les évaluations présentées ici ne valident pas intégralement les Unités d'Enseignement ou d'Apprentissages de la formation de l'étudiant en lien avec ces compétences.** Pour valider sa formation, l'étudiant doit valider les UE selon les règles de compensation propres à chaque établissement. Une partie des évaluations des UE porte sur des évaluations de ressources (connaissances...) et une autre directement sur les compétences à travers les mises en situations (saé, stage, alternance ou autre). **C'est uniquement cette partie d'évaluation qui porte sur les compétences qui est attestée ici.**

**Comment by isabelle-roy** [comment]
Fait
