### ISSUE TITLE
LL.	Améliorer la navigation des les pages des rapports dans portfolio enseignant

### ISSUE THREAD

**Issue by giraudin** [EsupPortail/KAPC#39]
Quand on arrive à la dernière page, impossible de savoir où on en est (il n’y a plus de « page X/Y). Le laisser pour se situer. Trouver une solution pour permettre de revenir facilement aux étudiants précédents.

**Comment by olivier-gerbe** [comment]
Le nombre de demandes par page n'a plus de raison d'être, toutes les demandes sont chargées.
