### ISSUE TITLE
C. Raccourcir la longueur des chargements des rapports enseignants

### ISSUE THREAD

**Issue by AdrienPrugnaud** [EsupPortail/KAPC#4]
Solutionner le temps trop long de rapports de demandes d’évaluation dès 60 étudiants. Il faut arriver à un résultat rapide pour des cohortes jusqu’à 400 demandes d’étudiants (400 demandes dans une même SAé). Pour l'instant, pour 100 étudiants cela prend environ 2 à 3 mn et on doit passer à 400 demandes en quelques secondes)
= enlever des infos : évaluation par l’étudiant, nombre de traces, ne pas chercher l’information dans le portfolio mais afficher une ligne. Possibilité, l’enseignant pourrait éditer dans la page de la SAE de l’étudiant avec les jumelles, vérifier que dans la SAé on voit le commentaire entre évaluateurs.

**Comment by olivier-gerbe** [comment]
Done
