### ISSUE TITLE
LL. Expliciter dans les pages exports de note (rechargement et csv)

### ISSUE THREAD

**Issue by giraudin** [EsupPortail/KAPC#40]
Dans le portfolio enseignant, exports de note pour chaque action, indiquer
- Sélectionnez des dates de début et fin de période puis rechargez le portfolio pour voir les résultats à l'aide du bouton à droite dans la barre noire qui contient le nom du ePortfolio
- Pour afficher correctement le fichier CSV exporté ouvrez le dans un logiciel de tableur qui affiche les CSV au format UTF-8...
(vérifier pour le format du CSV je ne suis pas certain)

**Comment by isabelle-roy** [comment]
J'ai ajouté une ligne pour le format utf8 à ce que j'avais déjà dans le modèle... à approuver par Éric.

**Comment by AdrienPrugnaud** [comment]
@giraudin

**Comment by AdrienPrugnaud** [comment]
@giraudin
