### ISSUE TITLE
NN. Changez Stages en stages et alternance dans plusieurs pages

### ISSUE THREAD

**Issue by giraudin** [EsupPortail/KAPC#41]
Quand l'enseignant se connecte et qu'il voit soit les 3 portfolios : saé... stages but... ePortfolio enseignant est-ce qu'il est possible ici aussi que stages but soit stages **et alternance** but...

Quand l'enseignant rentre sur le portfolio stages et alternances de but... dans les instructions il faudrait ajouter et de vos alternances   

- "Instructions. Les codes de vos stages **et de vos alternances** doivent vous être fournis par votre administrateur Karuta / ingénieur pédagogique (codes APOGEE). Ils sont utilisés pour envoyer les notes des étudiants à l'administration."

Dans la page Mes actions de etu2-info, il y a encore uniquement Les stages (mais c peut-être normal ???)
- Les stages **et l'alternance** sont considérés ici comme des actions particulières car il s'agit d'immersions professionnelles souvent plus complexes que les SAés. Il vous faudra les importer dans votre portfolio si votre formation a créé des fiches de stage **et d'alternance** et si ce n'est pas le cas vous devrez les créer vous même;

Dans le portfolio enseignants, renommez sous Exports, Exports des notes de stages **et d'alternance**

**Comment by isabelle-roy** [comment]
Tu dois avoir des anciennes versions de portfolios parce que je ne vois aucun changement à faire dans les modèles actuels...

**Comment by giraudin** [comment]
Bonjour Isabelle,

Sur etu2-info sur kapc.eportfolium.fr

Si tu le créés un nouvel étudiant je pourrai vérifier 

⁣Télécharger TypeApp pour Android ​

Le 20 nov. 2022, 15:59, à 15:59, Isabelle Roy ***@***.***> a écrit:
