### ISSUE TITLE
MM. Insérer logo AVENIR(s), France 2030, et mentions programme + financement anr...

### ISSUE THREAD

**Issue by giraudin** [EsupPortail/KAPC#42]
Insérer dans le portfolio étudiant et le portfolio enseignant les logos transmis par mail et le texte sur le programme France 2030 dans le bandeau noir en bas de page.

**Comment by isabelle-roy** [comment]
Pour France 2023 j'ai reçu un logo, pas un texte.
Si il y a un texte svp déposer ici.

**Comment by giraudin** [comment]
C'est ne texte que tu as deja placé sur le portfolio étudiant, reprends le même 

⁣Télécharger TypeApp pour Android ​

Le 20 nov. 2022, 16:00, à 16:00, Isabelle Roy ***@***.***> a écrit:
