### ISSUE TITLE
Fonctionnement des batchs et batchs multi formation

### ISSUE THREAD

**Issue by AdrienPrugnaud** [EsupPortail/KAPC#43]
Changer le fonctionnement d'alimentation des portfolios enseignants : 
- 1 batch permettant de créé le compte enseignant et son portfolio enseignant "sans rattachement"
- 1 batch multi formations (sous forme de zip ?) permettant le rajout de l'enseignant au x formations où il est évaluateur (et qu'il soit rajouter dans le répertoire évaluateur, dans le répertoire SAé et dans le répertoire stage des x formations)

**Comment by AdrienPrugnaud** [comment]
@jgribonvald as-tu des précisions à apporter ?

**Comment by jgribonvald** [comment]
Vu avec @olivier-gerbe 
Les enseignants sont forcément rattaché dans un dossier, mais après on lance un batch qui associe tout les enseignants aux différentes formations via un seul fichier csv.

Par contre : Révision des batchs enseignants pour permettre l'insertion via le minimum de fichiers.

**Comment by olivier-gerbe** [comment]
Fait
