### ISSUE TITLE
Permettre aux enseignants/auteur d'organiser l'ordre des SAés dans le répertoire de SAés

### ISSUE THREAD

**Issue by AdrienPrugnaud** [EsupPortail/KAPC#47]

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy pour l'instant seul le rôle designer peut organiser l'ordre des SAés qui ont été créées

**Comment by isabelle-roy** [comment]
@AdrienPrugnaud Je viens de l'ajouter dans le modèle mais tu vas devoir tester que ça n'a pas d'effet de bord : ce rôle est lié à d'autres rôles dans le back-end de Karuta. Je t'envoie une nouvelle version de KAPC 1.3 à tester d'ici la fin de la semaine.

**Comment by AdrienPrugnaud** [comment]
Super merci Isabelle.

Adrien

Le Mercredi 30 Novembre 2022 14:30 CET, Isabelle Roy ***@***.***> a écrit:
 
 
@AdrienPrugnaud Je viens de l'ajouter dans le modèle mais tu vas devoir tester que ça n'a pas d'effet de bord : ce rôle est lié à d'autres rôles dans le back-end de Karuta. Je t'envoie une nouvelle version de KAPC 1.3 à tester d'ici la fin de la semaine.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>


--

 Adrien PRUGNAUD / Chargé de mission ePortfolio
Port. +33 (0)6 49 17 61 ***@***.***

GIP Recia · Ressources numériques publiques en Centre-Val de Loire
Antenne de Touraine · 4-6, boulevard de Chinon · 37510 BALLAN-MIRÉ
Tél. 02 38 42 79 60
www.recia.fr ·
