### ISSUE TITLE
E. Paramètres de tri des évaluations

### ISSUE THREAD

**Issue by AdrienPrugnaud** [EsupPortail/KAPC#6]
L’ordre de tri dans les demandes d’évaluation pas clair, besoin de tri sur le nom de l’étudiant et dans l’idéal cumuler un tri sur le nom de la saé et ensuite sur le nom de l’étudiant pas le prénom comme actuellement = ok pour un tri sur le NOM (inversion prénom et nom) et étudier une piste javascript tri multi sélection pour voir si le cumul est possible (discussion Julien et Olivier) (essayer de faire pour KAPC 1.3)

**Comment by jgribonvald** [comment]
@jgribonvald doit fournir une lib js de tri multicolonne via sélecteur html
éch&nage avec @olivier-gerbe

**Comment by jgribonvald** [comment]
@olivier-gerbe il n'y a finalement pas besoin d'une lib, cf https://stackoverflow.com/questions/49956343/jquery-sort-table-by-multiple-column-values, il faut simplement avoir une implémentation pour la comparaison de deux paramètres. Le plus compliqué étant à gérer côté UI si on doit cumuler selon un ordre et une colonne défini par l'utilisateur.

**Comment by olivier-gerbe** [comment]
Fait. À tester

**Comment by AdrienPrugnaud** [comment]
Le tri par NOM (inversion prénom et nom) pour l'étudiant et la SAé par exemple fonctionne correctement
